name: Set up environment
description: Set up the environment for building and testing the library on a given platform

inputs:
  xcode:
    description: The version of Xcode to use
    required: true

runs:
  using: composite

  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777 # pin@v1.221.0
      with:
        ruby-version: '3.3.0'
        bundler-cache: true
        cache-version: 1

    - name: Install xcbeautify
      run: brew install xcbeautify
      shell: bash

    - name: Setup Xcode
      uses: mxcl/xcodebuild@6e60022a0cbe8c89278be2dd1773a2f68e7c5c87
      with:
        xcode: ${{ inputs.xcode }}
        action: none
        verbosity: xcbeautify
