name: Set up environment
description: Set up the environment for building and testing the library on a given platform

inputs:
  ruby:
    description: The version of Ruby to use
    required: true

  xcode:
    description: The version of Xcode to use
    required: true

runs:
  using: composite

  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@bbda85882f33075a3727c01e3c8d0de0be6146ce # pin@v1.224.0
      with:
        ruby-version: ${{ inputs.ruby }}
        bundler-cache: true
        cache-version: 1

    - name: Setup Xcode
      uses: mxcl/xcodebuild@75cd1d21e22129934f9ca289757708d8af9155f5 # pin@v3.4.0
      with:
        xcode: ${{ inputs.xcode }}
        action: none
        verbosity: xcbeautify
