coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - Auth0Tests/*
  status:
    patch:
      default:
        threshold: 50
        if_no_uploads: error
    project:
      default:
        target: auto
        threshold: 2
        if_no_uploads: error
    changes: false
comment: false
